"""Static pages generator — creates index.html for GitHub Pages.

Generates a static HTML page listing all available rule subscriptions
with direct links, format descriptions, and build statistics.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

log = logging.getLogger(__name__)

INDEX_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>adfilter — Rule Subscriptions</title>
    <style>
        :root {{
            --bg: #0d1117; --fg: #c9d1d9; --accent: #58a6ff;
            --card-bg: #161b22; --border: #30363d;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               background: var(--bg); color: var(--fg); padding: 2rem; line-height: 1.6; }}
        .container {{ max-width: 900px; margin: 0 auto; }}
        h1 {{ color: var(--accent); margin-bottom: 0.5rem; }}
        .subtitle {{ color: #8b949e; margin-bottom: 2rem; }}
        .stats {{ display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }}
        .stat-card {{ background: var(--card-bg); border: 1px solid var(--border);
                     border-radius: 8px; padding: 1rem 1.5rem; min-width: 150px; }}
        .stat-card .value {{ font-size: 1.5rem; font-weight: bold; color: var(--accent); }}
        .stat-card .label {{ font-size: 0.85rem; color: #8b949e; }}
        table {{ width: 100%; border-collapse: collapse; background: var(--card-bg);
                border-radius: 8px; overflow: hidden; border: 1px solid var(--border); }}
        th, td {{ padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid var(--border); }}
        th {{ background: #1c2128; font-weight: 600; }}
        a {{ color: var(--accent); text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .footer {{ margin-top: 2rem; font-size: 0.85rem; color: #8b949e; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>adfilter</h1>
        <p class="subtitle">Ad-filter rule aggregator & multi-format converter</p>
        <div class="stats">
            <div class="stat-card"><div class="value">{total_rules}</div><div class="label">Total Rules</div></div>
            <div class="stat-card"><div class="value">{file_count}</div><div class="label">Output Files</div></div>
            <div class="stat-card"><div class="value">{last_updated}</div><div class="label">Last Updated</div></div>
        </div>
        <table>
            <thead><tr><th>Format</th><th>Application</th><th>Subscribe</th></tr></thead>
            <tbody>
{table_rows}
            </tbody>
        </table>
        <p class="footer">Generated by <a href="https://github.com/Lknife666/adfilter">adfilter</a> &mdash; {generated_at}</p>
    </div>
</body>
</html>
"""

FORMAT_INFO = [
    ("dns.txt", "AdGuard Home DNS", "AdGuard Home, AdGuard DNS"),
    ("easylist.txt", "EasyList / ABP", "Adblock Plus, uBlock Origin, AdGuard"),
    ("clash.yaml", "Clash", "Clash, Clash Meta, Stash"),
    ("singbox.json", "sing-box", "sing-box rule-set (v2)"),
    ("surge.conf", "Surge", "Surge, Shadowrocket, Stash"),
    ("quantumult.conf", "Quantumult X", "Quantumult X"),
    ("loon.conf", "Loon", "Loon"),
    ("dnsmasq.conf", "dnsmasq", "dnsmasq, OpenWrt"),
    ("smartdns.conf", "smartdns", "SmartDNS"),
    ("hosts.txt", "hosts", "All OS, Pi-hole"),
    ("mikrotik.rsc", "MikroTik", "MikroTik RouterOS v6/v7"),
    ("unbound.conf", "Unbound", "Unbound DNS resolver"),
]


class PagesGenerator:
    """Generate static HTML pages for GitHub Pages deployment."""

    def __init__(
        self,
        *,
        rule_dir: str | Path = "./rule",
        base_url: str = "",
        repo: str = "Lknife666/adfilter",
    ) -> None:
        self.rule_dir = Path(rule_dir)
        self.base_url = base_url or f"https://raw.githubusercontent.com/{repo}/release"
        self.repo = repo

    def generate_index(self, output_path: str | Path | None = None) -> str:
        """Generate the index.html content.

        Args:
            output_path: if provided, write to this file path

        Returns:
            The generated HTML string
        """
        stats = self._load_stats()
        table_rows = self._build_table_rows()
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        html = INDEX_TEMPLATE.format(
            total_rules=stats.get("total_rules", "N/A"),
            file_count=stats.get("file_count", len(FORMAT_INFO)),
            last_updated=stats.get("last_updated", "N/A"),
            table_rows=table_rows,
            generated_at=generated_at,
        )

        if output_path:
            out = Path(output_path)
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(html, encoding="utf-8")
            log.info("PagesGenerator: wrote index.html to %s", out)

        return html

    def _load_stats(self) -> dict:
        """Load build stats from build-report.json."""
        report_path = self.rule_dir / "build-report.json"
        if not report_path.exists():
            return {}
        try:
            data = json.loads(report_path.read_text(encoding="utf-8"))
            return {
                "total_rules": data.get("total_rules", "N/A"),
                "file_count": data.get("file_count", len(FORMAT_INFO)),
                "last_updated": data.get("timestamp", "N/A"),
            }
        except (json.JSONDecodeError, OSError):
            return {}

    def _build_table_rows(self) -> str:
        """Build HTML table rows for each format."""
        rows = []
        for filename, fmt_name, apps in FORMAT_INFO:
            url = f"{self.base_url}/{filename}"
            row = (
                f'                <tr>'
                f'<td>{fmt_name}</td>'
                f'<td>{apps}</td>'
                f'<td><a href="{url}"><code>{filename}</code></a></td>'
                f'</tr>'
            )
            rows.append(row)
        return "\n".join(rows)
